[package]
name = "profiles"
version = "0.0.1"
authors = [ "hcij" ]
edition = "2018"

[lib]
name = "profiles"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
derive_more = "0"
serde = "1"
hdk = "0.0.100"
profiles = {git = "https://github.com/holochain-open-dev/profiles", rev="2e37a8a", package = "hc_zome_profiles"}