[package]
name = "request"
version = "0.0.1"
authors = [ "nkgardose" ]
edition = "2018"

[lib]
name = "request"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
derive_more = "0"
serde = "1"
hdk = "0.0.118"
holo_hash = {version = "*", features = ["encoding"]}