[package]
name = "preference"
version = "0.0.1"
authors = ["hcij"]
edition = "2018"

[lib]
name = "preference"
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = "0"
serde = "1"

hdk3 = "0"
